### ISSUE TITLE
3.5.0 problem Crossfire Micro

### ISSUE THREAD

**Issue by andrew16v** [ButterFlight/butterflight#144]
Hello,
 I have a problem and is that in version 3.5.0 at 30 meters i lose signal with my crossfire micro tx, tested all components probe with betaflight and here if it goes well.

 Do you know if there is a bug related to TBS Croosfire and Butterflight ??

Greetings and thank you.

**Comment by kidBrazil** [comment]
I am not aware of any bug at this time but will investigate.

**Comment by frakkan** [comment]
I have telemetry lost all the time with the crossfire nano.  No problem
with crossfire micro.  All has the latest software, and my quads running
3.5 fw.

On 6 May 2018 22:03, "Lucas Moreira" <notifications@github.com> wrote:

I am not aware of any bug at this time but will investigate.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ButterFlight/butterflight/issues/144#issuecomment-386909100>,
or mute the thread

**Comment by livid-fpv** [comment]
This sounds like a crossfire issue, the nano has had a rocky start
