### ISSUE TITLE
Systemconfig

### ISSUE THREAD

**Issue by robert-b** [ButterFlight/butterflight#71]
pid loop frequency is not settable for mpu-6000 fc's.
default setup always remains after booting.

works with betaflight but not with butterflight.

**Comment by robert-b** [comment]
i bought a realacc set with all components.
that set did include an omnibusf4sd.
which is no used for desktop flying.

i did load the defaults together with a binary from github making sure my changes do not interfere.
for me it fails using the 10.2.0 configurator.

**Comment by robert-b** [comment]
now i see clearer.
8/2 is max possible setting allowed for the mpu-6000.
what if you have an f7 - 8/8 is possible without question.

some sort of teaching what to use?

**Comment by ABLomas** [comment]
8K is max gyro rate on MPU6K, so 8/8 is possible (also something weird like 8/16 is possible on F4, but no sense to run pid loop faster than gyro readout).
8/8K runs on F4 omnibus without issues. Which exactly pid loop frequency is not settable?

**Comment by robert-b** [comment]
i can only select 8/2 as the max.
8/1 is possible - 8/8 not.
regardless if f4 or f7.

which version of the config tool do you run?

**Comment by ABLomas** [comment]
10.2.0
Maybe you run too many features and CPU could not keep with it, etc?
Try simple test - do "defaults" and just change looptime to 8/8. Should work.

**Comment by robert-b** [comment]
you explained what i did.

**Comment by ABLomas** [comment]
I think i know where your issue is.
I took Omnibus F4 board, flashed with F4SD FW (no difference between boards, only output mappings).
And yes, on defaults you cannot set PID loop higher than 2K, because ESC algo is set to "synced" by default and is set to ONESHOT125.
So, if you want to run synced - you can't use oneshot at higher than 2K speeds.
Solutions:

1. use DSHOT - and you can select 8/8
2. turn off synced ESC output mode - and you can select 8/8

IIRC this is even documented somewhere - def. not configurator/firmware issue.

**Comment by robert-b** [comment]
good point.
i will close the issue as it works.

**Comment by robert-b** [comment]
https://github.com/robert-b/butterfly
has some changes for the gyro and pid stuff ...
the new slewratefilter is active for all gyros.
for those hitting gates during a race ...
